// Types for GET POSTS
export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';

// Types for GET POSTS/Id
export const GET_SINGLE_POST = 'GET_SINGLE_POST'
export const GET_SINGLE_POST_SUCCESS = 'GET_SINGLE_POST_SUCCESS'
export const GET_SINGLE_POST_ERROR = 'GET_SINGLE_POST_ERROR'

// Types for PUT/ POST
export const UPDATE_POST = 'UPDATE_POST'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS' 
export const UPDATE_POST_ERROR = 'UPDATE_POST_ERROR'